### ISSUE TITLE
🧑‍💻 Add Admin and Contributos details in README File

### ISSUE THREAD

**Issue by Suryansh1720001** [RyanWalker277/HelpU#12]
Hello @RyanWalker277 

*Is your feature request related to a problem? Please describe.*
### Features that I want to add in README File

- Contributors details
- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive
- adding the footer part in readme file

*Describe the solution you'd like*

- Add new features

Kindly assign this issue to me under IWOC event with the label of medium.

**Comment by RyanWalker277** [comment]
Most of these features are already there in the readme. Also, IWOC dosent support these types of contributions. Try to do code contributions in order to learn something. Also, refrain from opening these kinds of issues which dont add an actual value to the project.
